name: Build & Push Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: nginx

jobs:

  push:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --tag ${{ github.actor }}/$IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ${{ github.actor }}/$IMAGE_NAME:latest
